development:
  adapter: postgresql
  encoding: utf8
  database: blog_development
  pool: 5
  username: blog
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: blog_test
  pool: 5
  username: blog
  password:
  min_messages: warning

production:
  adapter: postgresql
  encoding: utf8
  database: blog_production
  pool: 5
  username: blog
  password:
  